# Generated by Django 3.0.3 on 2020-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeauty', '0003_services_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
