# Generated by Django 3.0.3 on 2020-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeauty', '0005_addproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categories', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
